/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.ClienteControle;
import controle.FuncionarioControle;
import controle.PedidoControle;
import controle.PedidoItemControle;
import java.awt.Component;
import java.awt.event.KeyEvent;
import java.math.BigDecimal;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import modelo.Cliente;
import modelo.FuncionarioMAC;
import modelo.Pedido;
import modelo.PedidoItem;
import modelo.Produto;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import static org.jdesktop.observablecollections.ObservableCollections.observableList;
import util.Conexao;
import util.Tools;

/**
 *
 * @author Miquéias
 */
public class PedidoVisao extends javax.swing.JFrame {

    private Produto produtoPedido;
    private static int codigoUsuario;
    private static int codigoFuncionario;
    private static int codigoEmpresa;
    private Cliente clientePedido = null;
    private static FuncionarioMAC funcionario = null;
    private PedidoControle pedidoControle;
    private PedidoItemControle pedidoItemControle;
    private static Pedido pedido = null;
    private PedidoItem pedidoItem;
    private boolean fechar = true;
    private boolean novo = true;
    private List<PedidoItem> pedidoItemRemover = new ArrayList<>();
    private boolean flagNovoAlterarCliente = false;
    BigDecimal sub;
    BigDecimal acres = new BigDecimal("0");
    BigDecimal desc = new BigDecimal("0");
    BigDecimal total = new BigDecimal("0");

    /**
     * Creates new form Pedido
     *
     * @param codigoEmpresa
     * @param codigoUsuario
     */
    public PedidoVisao(int codigoEmpresa, int codigoUsuario) {
        initComponents();
        habilitaComponentes(false);
        setResizable(false);

        if (codigoEmpresa != 2) {
            System.exit(0);
        } else {
            pedidoControle = new PedidoControle();
            PedidoVisao.codigoUsuario = codigoUsuario;
            txtCodigo.requestFocus();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        produtoList = observableList(new ArrayList<modelo.Produto>());
        pedidoItemList = observableList(new ArrayList<modelo.PedidoItem>());
        panelDetalhes = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtVendedor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        dateVenda = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        dateVencimento = new com.toedter.calendar.JDateChooser();
        jlbCliente = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();
        btnBuscarCliente = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtComprador = new javax.swing.JTextField();
        btnBuscarFuncionario = new javax.swing.JButton();
        panelItens = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableItensPedido = new javax.swing.JTable();
        jlbPreco = new javax.swing.JLabel();
        jlbProduto = new javax.swing.JLabel();
        txtProduto = new javax.swing.JTextField();
        txtPrecoUnitario = new javax.swing.JFormattedTextField();
        jlbQuantidade = new javax.swing.JLabel();
        txtQuantidade = new javax.swing.JTextField();
        jlbQuantidade1 = new javax.swing.JLabel();
        txtIPI = new javax.swing.JTextField();
        btnAdicionar = new javax.swing.JButton();
        btnBuscarProduto = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        panelBotoes = new javax.swing.JPanel();
        btnNovo = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();
        btnComfirmar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnLocalizar = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        panelValores = new javax.swing.JPanel();
        jlbSubtotal = new javax.swing.JLabel();
        jlbDesconto = new javax.swing.JLabel();
        txtSubtotal = new javax.swing.JFormattedTextField();
        txtDesconto = new javax.swing.JFormattedTextField();
        jlbAcrescimo = new javax.swing.JLabel();
        txtAcrescimo = new javax.swing.JFormattedTextField();
        jlbTotal = new javax.swing.JLabel();
        txtTotal = new javax.swing.JFormattedTextField();
        jlbParcelas = new javax.swing.JLabel();
        txtFormaPagamento = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNotaFiscal = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObservacoes = new javax.swing.JTextArea();
        btnCalcular = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Pedido");
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        panelDetalhes.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Vendedor:");

        txtVendedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtVendedorKeyPressed(evt);
            }
        });

        jLabel2.setText("Data da Venda:");

        jLabel3.setText("Data Vencimento:");

        jlbCliente.setText("Cliente");

        txtCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtClienteKeyPressed(evt);
            }
        });

        btnBuscarCliente.setText("Buscar");
        btnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClienteActionPerformed(evt);
            }
        });

        jLabel7.setText("Comprador:");

        txtComprador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCompradorKeyPressed(evt);
            }
        });

        btnBuscarFuncionario.setText("Buscar");
        btnBuscarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarFuncionarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDetalhesLayout = new javax.swing.GroupLayout(panelDetalhes);
        panelDetalhes.setLayout(panelDetalhesLayout);
        panelDetalhesLayout.setHorizontalGroup(
            panelDetalhesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDetalhesLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(panelDetalhesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDetalhesLayout.createSequentialGroup()
                        .addGroup(panelDetalhesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(panelDetalhesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelDetalhesLayout.createSequentialGroup()
                                .addComponent(dateVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel3)
                                .addGap(5, 5, 5)
                                .addComponent(dateVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(panelDetalhesLayout.createSequentialGroup()
                                .addComponent(txtVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnBuscarFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())))
                    .addGroup(panelDetalhesLayout.createSequentialGroup()
                        .addGroup(panelDetalhesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbCliente)
                            .addComponent(jLabel7))
                        .addGap(34, 34, 34)
                        .addGroup(panelDetalhesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                            .addComponent(txtComprador))
                        .addGap(9, 9, 9)
                        .addComponent(btnBuscarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        panelDetalhesLayout.setVerticalGroup(
            panelDetalhesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDetalhesLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(panelDetalhesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(panelDetalhesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscarFuncionario)))
                .addGap(8, 8, 8)
                .addGroup(panelDetalhesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(dateVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(dateVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(panelDetalhesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbCliente)
                    .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelDetalhesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtComprador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelItens.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tableItensPedido.setColumnSelectionAllowed(true);
        tableItensPedido.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tableItensPedido.getTableHeader().setReorderingAllowed(false);

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, pedidoItemList, tableItensPedido);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${produto}"));
        columnBinding.setColumnName("Produto");
        columnBinding.setColumnClass(modelo.Produto.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${pedVendasProdQtde}"));
        columnBinding.setColumnName("Quant.");
        columnBinding.setColumnClass(Integer.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${pedVendasProdValor}"));
        columnBinding.setColumnName("R$ Unit.");
        columnBinding.setColumnClass(BigDecimal.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${pedVendasProdTotal}"));
        columnBinding.setColumnName("R$ Total");
        columnBinding.setColumnClass(BigDecimal.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${pedVendasProdIPI}"));
        columnBinding.setColumnName("IPI");
        columnBinding.setColumnClass(BigDecimal.class);
        columnBinding.setEditable(false);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane2.setViewportView(tableItensPedido);
        tableItensPedido.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tableItensPedido.getColumnModel().getColumnCount() > 0) {
            tableItensPedido.getColumnModel().getColumn(0).setResizable(false);
            tableItensPedido.getColumnModel().getColumn(0).setPreferredWidth(200);
            tableItensPedido.getColumnModel().getColumn(1).setResizable(false);
            tableItensPedido.getColumnModel().getColumn(1).setPreferredWidth(10);
            tableItensPedido.getColumnModel().getColumn(2).setResizable(false);
            tableItensPedido.getColumnModel().getColumn(2).setPreferredWidth(10);
            tableItensPedido.getColumnModel().getColumn(3).setResizable(false);
            tableItensPedido.getColumnModel().getColumn(3).setPreferredWidth(10);
            tableItensPedido.getColumnModel().getColumn(4).setResizable(false);
            tableItensPedido.getColumnModel().getColumn(4).setPreferredWidth(10);
        }

        jlbPreco.setText("Preço Unitário:");

        jlbProduto.setText("Produto:");

        txtProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtProdutoKeyPressed(evt);
            }
        });

        txtPrecoUnitario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPrecoUnitarioKeyPressed(evt);
            }
        });

        jlbQuantidade.setText("Quantidade:");

        txtQuantidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtQuantidadeKeyPressed(evt);
            }
        });

        jlbQuantidade1.setText("IPI:");

        txtIPI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIPIKeyPressed(evt);
            }
        });

        btnAdicionar.setText("Adicionar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        btnBuscarProduto.setText("Buscar");
        btnBuscarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProdutoActionPerformed(evt);
            }
        });

        btnRemover.setText("Remover");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelItensLayout = new javax.swing.GroupLayout(panelItens);
        panelItens.setLayout(panelItensLayout);
        panelItensLayout.setHorizontalGroup(
            panelItensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelItensLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelItensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(panelItensLayout.createSequentialGroup()
                        .addGroup(panelItensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelItensLayout.createSequentialGroup()
                                .addComponent(jlbPreco)
                                .addGap(18, 18, 18)
                                .addComponent(txtPrecoUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlbQuantidade)
                                .addGap(4, 4, 4)
                                .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jlbQuantidade1)
                                .addGap(4, 4, 4)
                                .addComponent(txtIPI, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelItensLayout.createSequentialGroup()
                                .addComponent(jlbProduto)
                                .addGap(47, 47, 47)
                                .addComponent(txtProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelItensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBuscarProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRemover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAdicionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        panelItensLayout.setVerticalGroup(
            panelItensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelItensLayout.createSequentialGroup()
                .addGroup(panelItensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelItensLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jlbProduto))
                    .addGroup(panelItensLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnBuscarProduto))
                .addGroup(panelItensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelItensLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(panelItensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelItensLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jlbPreco))
                            .addGroup(panelItensLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jlbQuantidade))
                            .addGroup(panelItensLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelItensLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jlbQuantidade1))
                            .addGroup(panelItensLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(txtIPI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnAdicionar)))
                    .addGroup(panelItensLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(txtPrecoUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRemover)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelBotoes.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        btnComfirmar.setText("Confirmar");
        btnComfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComfirmarActionPerformed(evt);
            }
        });

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnLocalizar.setText("Localizar");
        btnLocalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocalizarActionPerformed(evt);
            }
        });

        btnImprimir.setText("Imprimir");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBotoesLayout = new javax.swing.GroupLayout(panelBotoes);
        panelBotoes.setLayout(panelBotoesLayout);
        panelBotoesLayout.setHorizontalGroup(
            panelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNovo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAlterar)
                .addGap(6, 6, 6)
                .addComponent(btnComfirmar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnImprimir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLocalizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFechar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelBotoesLayout.setVerticalGroup(
            panelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAlterar)
                        .addComponent(btnNovo))
                    .addGroup(panelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnComfirmar)
                        .addComponent(btnLocalizar)
                        .addComponent(btnCancelar)
                        .addComponent(btnFechar)
                        .addComponent(btnImprimir)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelValores.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jlbSubtotal.setText("SubTotal:");

        jlbDesconto.setText("Desconto:");

        txtSubtotal.setEditable(false);
        txtSubtotal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        txtSubtotal.setEnabled(false);

        txtDesconto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDescontoKeyReleased(evt);
            }
        });

        jlbAcrescimo.setText("Acrescimo:");

        txtAcrescimo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAcrescimoKeyReleased(evt);
            }
        });

        jlbTotal.setText("Total:");

        txtTotal.setEditable(false);
        txtTotal.setEnabled(false);

        jlbParcelas.setText("Forma de Pagamento:");

        txtFormaPagamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFormaPagamentoKeyPressed(evt);
            }
        });

        jLabel4.setText("Nota Fiscal:");

        txtNotaFiscal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNotaFiscalKeyPressed(evt);
            }
        });

        jLabel5.setText("Observações:");

        txtObservacoes.setColumns(20);
        txtObservacoes.setRows(5);
        jScrollPane1.setViewportView(txtObservacoes);

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelValoresLayout = new javax.swing.GroupLayout(panelValores);
        panelValores.setLayout(panelValoresLayout);
        panelValoresLayout.setHorizontalGroup(
            panelValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelValoresLayout.createSequentialGroup()
                .addGroup(panelValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelValoresLayout.createSequentialGroup()
                        .addGroup(panelValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelValoresLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jlbParcelas)
                                .addGap(4, 4, 4)
                                .addComponent(txtFormaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jLabel4))
                            .addGroup(panelValoresLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jlbSubtotal)
                                .addGap(2, 2, 2)
                                .addComponent(txtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jlbDesconto)
                                .addGap(1, 1, 1)
                                .addComponent(txtDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addComponent(jlbAcrescimo)
                                .addGap(9, 9, 9)
                                .addComponent(txtAcrescimo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelValoresLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel5)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addGroup(panelValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelValoresLayout.createSequentialGroup()
                                .addComponent(jlbTotal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCalcular))
                            .addComponent(txtNotaFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 23, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelValoresLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        panelValoresLayout.setVerticalGroup(
            panelValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelValoresLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(panelValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtAcrescimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlbTotal)
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCalcular))
                    .addGroup(panelValoresLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(panelValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbSubtotal)
                            .addComponent(jlbDesconto)
                            .addComponent(jlbAcrescimo))))
                .addGap(7, 7, 7)
                .addGroup(panelValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNotaFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelValoresLayout.createSequentialGroup()
                        .addGroup(panelValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbParcelas)
                            .addComponent(txtFormaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel6.setText("Código do Pedido:");

        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodigoKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel6))
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelDetalhes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelItens, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelValores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDetalhes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelItens, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelValores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteActionPerformed
        String name = txtCliente.getText().trim();
        BuscaClienteVisao cbv = new BuscaClienteVisao(this, true, name);
        cbv.setVisible(true);
    }//GEN-LAST:event_btnBuscarClienteActionPerformed

    private void btnBuscarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProdutoActionPerformed
        String name = txtProduto.getText().trim();
        BuscaProdutoVisao pbv = new BuscaProdutoVisao(this, true, name);
        pbv.setVisible(true);
    }//GEN-LAST:event_btnBuscarProdutoActionPerformed

    private void txtQuantidadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQuantidadeKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtIPI.requestFocus();
        }
        txtQuantidade.setEditable(Tools.numberInputVerifier(this, evt, ""));
    }//GEN-LAST:event_txtQuantidadeKeyPressed

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        int qtd = txtQuantidade.getText().trim().isEmpty() ? 0 : Integer.parseInt(txtQuantidade.getText().trim());
        String preco = txtPrecoUnitario.getText().trim().isEmpty() ? "0" : txtPrecoUnitario.getText().trim();
        if (txtProduto.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Selecione um produto!", null, JOptionPane.INFORMATION_MESSAGE);
        } else if (qtd == 0) {
            JOptionPane.showMessageDialog(null, "Informe uma quantidade válida!", null, JOptionPane.INFORMATION_MESSAGE);
        } else if (preco.equals("0")) {
            JOptionPane.showMessageDialog(null, "Informe um preço válido!", null, JOptionPane.INFORMATION_MESSAGE);
        } else {

            pedidoItem = new PedidoItem();
            pedidoItem.setProduto(produtoPedido);
            pedidoItem.setPedVendasProdQtde(qtd);
            pedidoItem.setPedVendasProdValor(new BigDecimal(preco));
            pedidoItem.setGrupoCodigo(pedidoItem.getProduto().getGrupoEstCodigo());
            pedidoItem.setPedVendasProdTotal((pedidoItem.getPedVendasProdValor().multiply(new BigDecimal("" + pedidoItem.getPedVendasProdQtde()))));
            pedidoItem.setPedidoVendaCodigo(pedido.getPedidoVendaCodigo());
            pedidoItem.setPedVendasProdIPI(new BigDecimal(txtIPI.getText().trim().isEmpty() ? "0" : txtIPI.getText().trim()));
            pedidoItem.setEmpCodigo(2);

            validaProduto(pedidoItem);
            //pedidoItemList.add(pedidoItem);
            sub = new BigDecimal("0");
            pedidoItemList.forEach((i) -> {
                sub = sub.add(i.getPedVendasProdTotal());
            });
            txtSubtotal.setText(sub.toString());

            clearProduct();
            calculaTotal();
            //updateTable();
        }
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void txtPrecoUnitarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecoUnitarioKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtQuantidade.requestFocus();
        }
        txtPrecoUnitario.setEditable(Tools.numberInputVerifier(this, evt, "."));
    }//GEN-LAST:event_txtPrecoUnitarioKeyPressed

    private void txtIPIKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIPIKeyPressed
        txtIPI.setEditable(Tools.numberInputVerifier(this, evt, "."));
    }//GEN-LAST:event_txtIPIKeyPressed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        habilitaComponentes(true);
        limpaCampos();
        novo = true;
        pedido = new Pedido();
        pedidoItemControle = new PedidoItemControle();
        pedido.setPedidoVendaCodigo(PedidoControle.geraCodigo());
        txtCodigo.setText("" + pedido.getPedidoVendaCodigo());
        txtCodigo.setEnabled(false);
        txtVendedor.requestFocus();
        flagNovoAlterarCliente = true;
        fechar = false;
        dateVenda.setDate(new Date());
        dateVencimento.setDate(new Date());
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        int res = JOptionPane.showConfirmDialog(this, "Deseja realmente cancelar ?");
        if (res == 0) {
            flagNovoAlterarCliente = false;

            habilitaComponentes(false);
            fechar = true;
            limpaObjetos();
            limpaCampos();
            txtCodigo.setEnabled(true);
            preencheFuncionario();
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        if (fechar) {
            System.exit(0);
        } else {
            JOptionPane.showMessageDialog(this, "É necessário Confirmar/Cancelar para Fechar!");
        }
    }//GEN-LAST:event_btnFecharActionPerformed

    private void btnComfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComfirmarActionPerformed
        if (pedido != null) {
            if (txtCliente.getText().trim().isEmpty() || clientePedido == null) {
                JOptionPane.showMessageDialog(null, "Selecione um Cliente");
                txtCliente.requestFocus();
            } else if (dateVenda.getDate() == null) {
                JOptionPane.showMessageDialog(null, "Informe a data da venda");
                dateVenda.requestFocus();
            } else if (dateVencimento.getDate() == null) {
                JOptionPane.showMessageDialog(null, "Informe a data do vencimento");
                dateVencimento.requestFocus();
            } else if (txtVendedor.getText().trim().isEmpty() || funcionario == null) {
                JOptionPane.showMessageDialog(null, "Selecione um Vendedor");
                txtVendedor.requestFocus();
            } else {

                populaPedido();

                try {

                    if (novo) {
                        pedidoControle.save(pedido);
                        pedidoItemList.forEach((item) -> {
                            pedidoItemControle.save(item);
                        });
                    } else {
                        pedidoControle.update(pedido);
                        pedidoItemList.forEach((item) -> {
                            pedidoItemControle.update(item);
                        });
                        pedidoItemRemover.forEach((item) -> {
                            pedidoItemControle.delete(item);
                        });
                    }
                    int op = JOptionPane.showConfirmDialog(this, "Deseja imprimir/visualizar o pedido?");
                    if (op == 0) {
                        report(pedido.getPedidoVendaCodigo());
                    }

                    limpaObjetos();
                    limpaCampos();
                    habilitaComponentes(false);

                    flagNovoAlterarCliente = false;
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Falha ao gravar as informações!\nErro:" + e, null, JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_btnComfirmarActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        calculaTotal();
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        if (BuscaPedidoVisao.pedido == null) {
            try {
                setCliente();
            } catch (Exception e) {
            }
            try {
                setProduto();
            } catch (Exception e) {
            }
            try {
                setFuncionario();
            } catch (Exception e) {
            }
        } else {
            preencheCampos(BuscaPedidoVisao.pedido);
            BuscaPedidoVisao.pedido = null;
        }
    }//GEN-LAST:event_formWindowGainedFocus

    private void txtCodigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyPressed
        txtCodigo.setEditable(Tools.numberInputVerifier(this, evt, ""));
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            Pedido p = PedidoControle.buscaPorCodigo(Integer.parseInt(txtCodigo.getText().trim()));
            if (p != null) {
                if (p.getPedidoVendaCodigo() > 0) {
                    preencheCampos(p);
                }
            }else{
                limpaCampos();
                limpaObjetos();
            }
        }
    }//GEN-LAST:event_txtCodigoKeyPressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        pack();
    }//GEN-LAST:event_formWindowOpened

    private void btnLocalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocalizarActionPerformed
        BuscaPedidoVisao buscaPedidoVisao = new BuscaPedidoVisao(this, true, PedidoVisao.codigoUsuario);
        buscaPedidoVisao.setVisible(true);
    }//GEN-LAST:event_btnLocalizarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        if (txtCodigo.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Informe o codigo do pedido");
        } else {
            if ((!txtCodigo.getText().trim().isEmpty())) {
                PedidoVisao.pedido = PedidoControle.buscaPorCodigo(Integer.parseInt(txtCodigo.getText().trim()));
                if (PedidoVisao.pedido != null) {
                    if (PedidoVisao.pedido.getPedidoVendaCodigo() > 0) {
                        preencheCampos(PedidoVisao.pedido);
                        if (PedidoControle.permiteAlterarExcluir(codigoUsuario)) {
                            novo = false;
                            habilitaComponentes(true);
                            flagNovoAlterarCliente = true;
                            fechar = false;
                            pedidoItemControle = new PedidoItemControle();
                            txtCodigo.setEnabled(false);
                        } else {
                            JOptionPane.showMessageDialog(this, "Você não possui permissão para altereção!");
                        }
                    }
                }
            }

        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        int linha = tableItensPedido.getSelectedRow();
        if (linha != -1) {
            int op = JOptionPane.showConfirmDialog(this, "Deseja realmente remover?");
            if (op == 0) {
                pedidoItemRemover.add(pedidoItemList.get(linha));
                pedidoItemList.remove(linha);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um item para remover!");
        }
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        if (txtCodigo.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Informe o codigo do pedido");
        } else {
            if ((!txtCodigo.getText().trim().isEmpty())) {
                pedido = PedidoControle.buscaPorCodigo(Integer.parseInt(txtCodigo.getText().trim()));
                if (pedido != null) {
                    if (pedido.getPedidoVendaCodigo() > 0) {
                        report(pedido.getPedidoVendaCodigo());
                    }
                }
            }
        }
    }//GEN-LAST:event_btnImprimirActionPerformed

    private void btnBuscarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarFuncionarioActionPerformed
        String name = txtVendedor.getText().trim();
        BuscaFuncionarioVisao bfv = new BuscaFuncionarioVisao(this, true, name);
        bfv.setVisible(true);
    }//GEN-LAST:event_btnBuscarFuncionarioActionPerformed

    private void txtDescontoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescontoKeyReleased
        if (!txtDesconto.getText().trim().isEmpty()) {
            btnCalcular.setEnabled(true);
        } else if (txtDesconto.getText().trim().isEmpty() && txtAcrescimo.getText().trim().isEmpty()) {
            btnCalcular.setEnabled(false);
        }
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtAcrescimo.requestFocus();
        }
    }//GEN-LAST:event_txtDescontoKeyReleased

    private void txtAcrescimoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAcrescimoKeyReleased
        if (!txtAcrescimo.getText().trim().isEmpty()) {
            btnCalcular.setEnabled(true);
        } else if (txtAcrescimo.getText().trim().isEmpty() && txtDesconto.getText().trim().isEmpty()) {
            btnCalcular.setEnabled(false);
        }
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtFormaPagamento.requestFocus();
        }
    }//GEN-LAST:event_txtAcrescimoKeyReleased

    private void txtProdutoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProdutoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnBuscarProdutoActionPerformed(null);
        }
    }//GEN-LAST:event_txtProdutoKeyPressed

    private void txtVendedorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVendedorKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnBuscarFuncionarioActionPerformed(null);
        }
    }//GEN-LAST:event_txtVendedorKeyPressed

    private void txtCompradorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCompradorKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtProduto.requestFocus();
        }
    }//GEN-LAST:event_txtCompradorKeyPressed

    private void txtClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClienteKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnBuscarClienteActionPerformed(null);
        }
    }//GEN-LAST:event_txtClienteKeyPressed

    private void txtFormaPagamentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFormaPagamentoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtNotaFiscal.requestFocus();
        }
    }//GEN-LAST:event_txtFormaPagamentoKeyPressed

    private void txtNotaFiscalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNotaFiscalKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtObservacoes.requestFocus();
        }
    }//GEN-LAST:event_txtNotaFiscalKeyPressed

    private BigDecimal totalProdutos() {
        BigDecimal res = new BigDecimal("0");
        for (PedidoItem item : pedidoItemList) {
            res = res.add(item.getPedVendasProdTotal());
        }
        return res;
    }

    @SuppressWarnings("unchecked")
    private void report(int codigo) {
        Connection con = Conexao.getConnection();
        String src = "reports\\ReportPedidoMAC.jasper";
        JasperPrint print = null;
        Map parametros = new HashMap();
        parametros.put("CodigoVenda", codigo);
        try {
            print = JasperFillManager.fillReport(src, parametros, con);
            JasperViewer view = new JasperViewer(print, false);
            view.setVisible(true);
        } catch (JRException ex) {
            JOptionPane.showMessageDialog(this, "Não foi possível abrir  visualização!\nErro: " + ex.getMessage());
        }

    }

    private void populaPedido() {
        pedido.setEmpCodigo(2);
        pedido.setPFisicaCodigoFunc(PedidoVisao.funcionario.getpFisicaCodigo());
        pedido.setPessoaCodigoFunc(PedidoVisao.funcionario.getPessoaCodigo());
        pedido.setPedidoVendaAcrescimo(txtAcrescimo.getText().trim().isEmpty() ? new BigDecimal("0") : new BigDecimal(txtAcrescimo.getText().trim()));
        pedido.setPedidoVendaData(dateVenda.getDate());
        pedido.setPedidoVendaDesconto(txtDesconto.getText().trim().isEmpty() ? new BigDecimal("0") : new BigDecimal(txtDesconto.getText().trim()));
        pedido.setPedidoVendaFormaPagamento(txtFormaPagamento.getText().trim());
        pedido.setPedidoVendaNumeroNota(txtNotaFiscal.getText().trim());
        pedido.setPedidoVendaObservacao(txtObservacoes.getText().trim());
        pedido.setPedidoVendaTotalProdutos(totalProdutos());
        pedido.setPedidoVendaTotalPedido(total);
        pedido.setPedidoVendaVencimento(dateVencimento.getDate());
        pedido.setCliente(ClienteControle.buscaPorCodigo(clientePedido.getpCodigo()));
        pedido.setPedidoVendaComprador(txtComprador.getText().trim());
        pedido.setPedidoVendaUsuarioRegistro(PedidoVisao.codigoUsuario);
        pedido.setPessoaFJCodigoCliente(1);

    }

    private void preencheFuncionario() {
        txtVendedor.setText(PedidoVisao.codigoFuncionario + " - " + PedidoControle.buscaNomeFuncionario(codigoUsuario));
    }

    private void setCliente() {

        clientePedido = BuscaClienteVisao.cliente;
        txtCliente.setText(BuscaClienteVisao.cliente.getNomeRazaoSocial());
        if (flagNovoAlterarCliente) {
            pedido.setCliente(ClienteControle.buscaPorCodigo(clientePedido.getpCodigo()));
            pedido.setPessoaFJCodigoCliente(1);
        }
    }

    private void setFuncionario() {
        PedidoVisao.funcionario = BuscaFuncionarioVisao.funcionario;
        if (PedidoVisao.funcionario != null) {
            txtVendedor.setText(PedidoVisao.funcionario.getPessoaCodigo() + " - " + PedidoVisao.funcionario.getNomeFuncionario());
        }
    }

    private void setProduto() {
        produtoPedido = BuscaProdutoVisao.produto;
        txtProduto.setText(produtoPedido.getProdEstDescricao());
    }

    private void preencheCampos(Pedido pedido) {
        if (pedido != null) {

            //txtVendedor.setText("" + pedido.getPessoaCodigoFunc() + " - " + PedidoControle.buscaNomeFuncionario(pedido.getPessoaCodigoFunc()));
            dateVenda.setDate(pedido.getPedidoVendaData());
            dateVencimento.setDate(pedido.getPedidoVendaVencimento());
            clientePedido = ClienteControle.buscaPorCodigo(pedido.getCliente().getpCodigo());
            PedidoVisao.funcionario = FuncionarioControle.buscaPorCodigoPessoa(pedido.getPessoaCodigoFunc());
            PedidoVisao.codigoFuncionario = PedidoVisao.funcionario.getPessoaCodigo();
            PedidoVisao.codigoUsuario = PedidoVisao.funcionario.getUsuCodigo();
            //PedidoVisao.pedido = pedido;
            preencheFuncionario();
            txtCliente.setText(clientePedido.getNomeRazaoSocial());
            txtCodigo.setText("" + pedido.getPedidoVendaCodigo());
            pedidoItemList.clear();
            pedidoItemList.addAll(PedidoItemControle.buscaTodos(pedido.getPedidoVendaCodigo()));

            //System.out.println(pedido.getPedidoVendaTotalProdutos());
            sub = pedido.getPedidoVendaTotalProdutos();
            desc = pedido.getPedidoVendaDesconto();
            acres = pedido.getPedidoVendaAcrescimo();
            txtSubtotal.setText(sub.toString());
            txtDesconto.setText(desc.toString());
            txtAcrescimo.setText(acres.toString());
            total = pedido.getPedidoVendaTotalPedido();
            txtTotal.setText(total.toString());
            txtFormaPagamento.setText(pedido.getPedidoVendaFormaPagamento());
            txtNotaFiscal.setText(pedido.getPedidoVendaNumeroNota());
            txtObservacoes.setText(pedido.getPedidoVendaObservacao());
            txtComprador.setText(pedido.getPedidoVendaComprador());
            //calculaTotal();
        }

    }

    private void calculaTotal() {

        if (txtDesconto.getText().isEmpty() && !txtAcrescimo.getText().isEmpty()) {
            acres = new BigDecimal(txtAcrescimo.getText().trim());
            //total = sub + acres;
            total = sub.add(acres);
            txtTotal.setText(total.toString());
        } else if (!txtDesconto.getText().isEmpty() && txtAcrescimo.getText().isEmpty()) {
            desc = new BigDecimal(txtDesconto.getText().trim());
            total = sub.subtract(desc);
            txtTotal.setText(total.toString());
        } else if (!txtDesconto.getText().isEmpty() && !txtAcrescimo.getText().isEmpty()) {
            desc = new BigDecimal(txtDesconto.getText().trim());
            acres = new BigDecimal(txtAcrescimo.getText().trim());
            total = (sub.subtract(desc)).add(acres);
            txtTotal.setText(total.toString());
        } else if (txtDesconto.getText().isEmpty() && txtAcrescimo.getText().isEmpty()) {
            total = total.add(sub);
            txtTotal.setText(total.toString());
        }
    }

    private void validaProduto(PedidoItem item) {
        boolean val = true;
        PedidoItem iv;
        PedidoItem novoItem;
        for (int i = 0; i < pedidoItemList.size(); i++) {
            iv = pedidoItemList.get(i);
            if (iv.getProduto().getProdEstDescricao().equals(item.getProduto().getProdEstDescricao())) {
                novoItem = iv;
                sub.subtract(iv.getPedVendasProdTotal());
                pedidoItemList.remove(i);
                novoItem.setPedVendasProdQtde(novoItem.getPedVendasProdQtde() + item.getPedVendasProdQtde());
                novoItem.setPedVendasProdTotal(novoItem.getPedVendasProdTotal().add(item.getPedVendasProdTotal()));
                pedidoItemList.add(i, novoItem);
                val = false;
            }
        }
        if (val) {
            pedidoItemList.add(item);
        }

    }

    private void habilitaComponentes(boolean status) {

        txtObservacoes.setEnabled(status);
        btnNovo.setEnabled(!status);
        btnImprimir.setEnabled(!status);
        btnLocalizar.setEnabled(!status);
        btnAlterar.setEnabled(!status);
        txtCodigo.setEnabled(!status);
        btnBuscarCliente.setEnabled(!btnNovo.isEnabled());
        btnBuscarProduto.setEnabled(!btnNovo.isEnabled());
        btnAdicionar.setEnabled(!btnNovo.isEnabled());
        tableItensPedido.setEnabled(!btnNovo.isEnabled());
        btnCancelar.setEnabled(status);
        btnComfirmar.setEnabled(!btnNovo.isEnabled());

        for (Component c : panelDetalhes.getComponents()) {
            c.setEnabled(status);
        }
        for (Component c : panelItens.getComponents()) {
            c.setEnabled(status);
        }
        for (Component c : panelValores.getComponents()) {
            c.setEnabled(status);
        }
        btnCalcular.setEnabled(false);

    }

    private void clearProduct() {
        txtProduto.setText("");
        produtoPedido = null;
        BuscaProdutoVisao.produto = null;
        txtQuantidade.setText("");
        txtIPI.setText("");
        txtPrecoUnitario.setText("");
    }

    private void limpaObjetos() {
        BuscaClienteVisao.cliente = null;
        BuscaProdutoVisao.produto = null;
        BuscaPedidoVisao.pedido = null;
        BuscaFuncionarioVisao.funcionario = null;
        clientePedido = null;
        produtoPedido = null;
        pedido = null;
        funcionario = null;
    }

    private void limpaCampos() {

        txtCodigo.setText("");
        txtVendedor.setText("");
        txtCliente.setText("");
        txtComprador.setText("");

        txtProduto.setText("");
        txtPrecoUnitario.setText("");
        txtQuantidade.setText("");
        txtIPI.setText("");
        pedidoItemList.clear();

        txtSubtotal.setText("");
        txtDesconto.setText("");
        txtAcrescimo.setText("");
        txtTotal.setText("");
        txtFormaPagamento.setText("");
        txtNotaFiscal.setText("");
        txtObservacoes.setText("");
        total = new BigDecimal("0");
        sub = new BigDecimal("0");
        desc = new BigDecimal("0");
        acres = new BigDecimal("0");
        fechar = true;

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        if (args.length > 0) {
            codigoEmpresa = Integer.parseInt(args[0]);
            codigoUsuario = Integer.parseInt(args[1]);
        } else {
            codigoEmpresa = 2;
            codigoUsuario = 294;

        }
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        try {

            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PedidoVisao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PedidoVisao(codigoEmpresa, codigoUsuario).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JButton btnBuscarFuncionario;
    private javax.swing.JButton btnBuscarProduto;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnComfirmar;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnLocalizar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnRemover;
    private com.toedter.calendar.JDateChooser dateVencimento;
    private com.toedter.calendar.JDateChooser dateVenda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jlbAcrescimo;
    private javax.swing.JLabel jlbCliente;
    private javax.swing.JLabel jlbDesconto;
    private javax.swing.JLabel jlbParcelas;
    private javax.swing.JLabel jlbPreco;
    private javax.swing.JLabel jlbProduto;
    private javax.swing.JLabel jlbQuantidade;
    private javax.swing.JLabel jlbQuantidade1;
    private javax.swing.JLabel jlbSubtotal;
    private javax.swing.JLabel jlbTotal;
    private javax.swing.JPanel panelBotoes;
    private javax.swing.JPanel panelDetalhes;
    private javax.swing.JPanel panelItens;
    private javax.swing.JPanel panelValores;
    private java.util.List<modelo.PedidoItem> pedidoItemList;
    private java.util.List<modelo.Produto> produtoList;
    private javax.swing.JTable tableItensPedido;
    private javax.swing.JFormattedTextField txtAcrescimo;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtComprador;
    private javax.swing.JFormattedTextField txtDesconto;
    private javax.swing.JTextField txtFormaPagamento;
    private javax.swing.JTextField txtIPI;
    private javax.swing.JTextField txtNotaFiscal;
    private javax.swing.JTextArea txtObservacoes;
    private javax.swing.JFormattedTextField txtPrecoUnitario;
    private javax.swing.JTextField txtProduto;
    private javax.swing.JTextField txtQuantidade;
    private javax.swing.JFormattedTextField txtSubtotal;
    private javax.swing.JFormattedTextField txtTotal;
    private javax.swing.JTextField txtVendedor;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
